apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  namespace: app
  labels:
    app: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      name: warehouse
      labels:
        app: warehouse
    spec:
      containers:
        - name: warehouse
          image: gamma86/warehouse:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: warehouse-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: warehouse-secrets
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-secrets
                  key: spring.datasource.password
      restartPolicy: Always
      